Sales table date fileter
solid-adventure/trivial-ui pull request #131
Opened 2024-08-07 21:12 UTC by goranradmanovic

Fixing date filter on Sales table and small fix for info msg. when org. is not selected

@vgkids Please check this open PR

2024-08-22 22:22 UTC, vgkids requested changes

2024-08-22 22:22 UTC, vgkids commented on src/views/SalesView.vue
>  						})
@goranradmanovic This doesn't look right, I was under the impression the issue was that we need to expand the "dateIs" and "dateIsNot" to be send a pair of ranges that cover a 24 hour period. This look like it would swap one very specific moment in time for another.

2024-09-03 09:04 UTC, goranradmanovic commented on src/views/SalesView.vue
>  						})
@vgkids I'm sending the 'dateIs' and 'dateIsNot' as array of objects.
![decoded](https://github.com/user-attachments/assets/0edb84b3-232e-4344-86f1-2772be603f0c)
![datefilter](https://github.com/user-attachments/assets/aa660274-0fae-4e8d-9ef2-f696d30e3872)

2024-09-03 17:33 UTC, drowninginflowers commented on src/views/SalesView.vue
>  						})
@goranradmanovic That doesn't seem right. The issue here is that currently we specify the `dateIs` rule as something like the following when filtering to a single day:
```
[
  {
    c: 'originated_at',
    o: '=',
    p: '2023-08-15T00:00:00'
  }
]
```
This isn't correct though because it will only return data whose exact `originated_at` is the given date and time, so 00:00:00 exactly. Instead, we'd like to pass in a filter like this:
```
[
  {
    c: 'originated_at',
    o: '>=', // here we use greater than or equals to include midnight of 2023-08-15
    p: '2023-08-15T00:00:00'
  },
  {
    c: 'originated_at',
    o: '<', // here we use strict less than to exclude midnight of 2023-08-16
    p: '2023-08-16T00:00:00'
  }
]
```
This filter array will return any data whose `originated_at` is between midnight of 2023-08-15 and midnight of 2023-08-16 which encompasses the entire date of 2023-08-15

`dateIsNot` is currently logically impossible to execute with a single API call because the filters use AND logic to stack with each other. I would recommend removing this filter option, or using 2 API calls and removing the ability to combine it with other filter rules in the UI.

2024-09-04 08:50 UTC, goranradmanovic commented on src/views/SalesView.vue
>  						})
@drowninginflowers 

Can you check now this branch with new changes, now date sreach parma is this
%5B%7B%22c%22%3A%22originated_at%22%2C%22o%22%3A%22%3E%3D%22%2C%22p%22%3A%222024-08-31T22%3A00%3A00.000Z%22%7D%2C%7B%22c%22%3A%22originated_at%22%2C%22o%22%3A%22%3C%22%2C%22p%22%3A%222024-09-02T22%3A00%3A00.000Z%22%7D%5D

![date1](https://github.com/user-attachments/assets/bfd4e870-02cf-40c1-8383-0fb993c27473)
![dec1](https://github.com/user-attachments/assets/49096c79-b327-49b9-8048-0b5a681060c7)

2024-09-04 15:58 UTC, drowninginflowers commented on src/views/SalesView.vue
>  						})
@goranradmanovic This is still not quite right as you can see from my screenshot 
![image](https://github.com/user-attachments/assets/3dbcf938-02df-49b9-b34c-8345dd651a97)
Currently the dateIs filter produces this search by itself:
```
[
  {
    c: 'originated_at',
    o: '>=',
    p: '2023-23-17T00:00:00'
  }
]
```
The `dateIs` rule should, by itself, instead create the following search for `dateIs = 2023-12-17`:
```
[
  {
    c: 'originated_at',
    o: '=',
    p: '2023-12-17T00:00:00'
  },
  {
    c: 'originated_at',
    o: '<',
    p: '2023-12-18T00:00:00'
  }
]
```

2024-09-04 16:17 UTC, vgkids commented
While we're refining this– we also need to not send the date filter across the API unless the user has set a date filter.

Currently, with no filter set, we're sending a 100 year range:

```
{
  register_id: 1,
  start_at: "2000-09-04T16:14:40.364Z",
  end_at: "2100-09-04T16:14:40.364Z"
}
```

If we leave start_at and end_at off the request instead, the DB query goes from 5000ms to 85ms.

2024-09-10 12:14 UTC, goranradmanovic commented
@vgkids and @drowninginflowers Please check this new cahnges for 'dateIs' filter on Sales table

![dateisdecoded](https://github.com/user-attachments/assets/a9f1ddd6-2172-445a-b16d-4ef52d03773c)
![dateis](https://github.com/user-attachments/assets/d962e3d5-9b64-4092-97bf-a797e42319c7)

URL param ( %5B%7B%22c%22%3A%22originated_at%22%2C%22o%22%3A%22%3E%3D%22%2C%22p%22%3A%222024-09-03T00%3A00%3A00-05%3A00%22%7D%2C%7B%22c%22%3A%22originated_at%22%2C%22o%22%3A%22%3C%22%2C%22p%22%3A%222024-09-04T00%3A00%3A00-05%3A00%22%7D%5D )

Decoded URL param ( [{"c":"originated_at","o":">=","p":"2024-09-03T00:00:00-05:00"},{"c":"originated_at","o":"<","p":"2024-09-04T00:00:00-05:00"}] )

2024-09-11 00:22 UTC, vgkids approved these changes
Looks good, thanks for slugging it out on this @goranradmanovic and @drowninginflowers.

2024-09-11 00:36 UTC, merged