Addressing comments for the first pass on Contracts list page
solid-adventure/trivial-ui pull request #151
Opened 2024-09-11 06:57 UTC by goranradmanovic

@vgkids Please check this new PR for Contract List page

2024-09-11 19:37 UTC, vgkids requested changes

2024-09-11 19:37 UTC, vgkids commented on src/views/ContractsView.vue
> +          item.barHeight = ((item?.count['500'] || 0) + (item?.count['200'] || 0)) || 1 // Default bar chart hight is 1px
We want the bar height to be proportional for the total amount of activity.

Here's a method that gives you the total amount of activity from the `/stats/` response, and also its proportional bar height. The day with the highest activity will have `proportionalHeight: 100`.

If there are errors, the bar height should still be the same, but the bar will be red.

``` javascript
const addProportionalHeightAndTotal = (data) => {
  // Calculate total count for each day and find the maximum
  const maxTotal = data.reduce((max, item) => {
    const total = Object.values(item.count).reduce((sum, value) => sum + value, 0);
    return Math.max(max, total);
  }, 0);

  // Add proportional height and total to each item
  return data.map(item => {
    const total = Object.values(item.count).reduce((sum, value) => sum + value, 0);
    const proportionalHeight = Math.round((total / maxTotal) * 100);
    return {
      ...item,
      count: {
        ...item.count,
        total
      },
      proportionalHeight
    };
  });
};
```

2024-09-11 19:42 UTC, vgkids commented
Full list:

- bar height should be proportional to total activity
- the table is scrolling inside a container, even though there's plenty of page unused
- the tooltip is obscured by whatever this inner container is
![Screenshot 2024-09-11 at 12 37 40 PM](https://github.com/user-attachments/assets/62a2c6c3-5cf9-46e7-9f43-ae1137f617d8)
- Let's add this Filter / Search bar from the existing contracts page using the same matching, it is very helpful for a quick narrowing of results, without having to use the column filters.
![Screenshot 2024-09-11 at 12 40 50 PM](https://github.com/user-attachments/assets/c0ae3e47-f829-47e3-961e-f82c00d2352b)

2024-09-16 09:21 UTC, goranradmanovic commented
@vgkids Please check new changes on this PR based on your last commets and loom video

2024-09-16 20:08 UTC, vgkids approved these changes
Looks great. I made the links in the sidebar and breadcrumb point to the new path, and squashed @goranradmanovic's commits into one.

We'll want to re-visit the path name later; the quick `add-a-3-on-the-end` versioning here (done at my request) is fast but will catch up with us eventually.

2024-09-16 20:09 UTC, merged