First draft of transfer apps
solid-adventure/trivial-ui pull request #68
Opened 2024-02-16 21:26 UTC by elmerv

2024-02-26 17:25 UTC, vgkids requested changes
Minor tweaks, looks good overall.

2024-02-26 17:25 UTC, vgkids commented on source/components/builderv2/AppTransferManager.vue
> +        this.organization_name = org_name
A method named `isOwner` should return a true/false answer, and not perform a change while it does the lookup.

If you make `organization_name` a computed property, you don't need to set it at all.

2024-02-26 17:25 UTC, vgkids commented on source/components/builderv2/AppTransferManager.vue
> +      owner_type: (state) => state.app.owner_type,
Make the naming convention match. The matching pair of  `current_owner_id` would be `current_owner_type`.

2024-02-26 18:25 UTC, elmerv commented on source/components/builderv2/AppTransferManager.vue
> +        this.organization_name = org_name
I just spent some time learning about computed properties, but I can't figure out how implementing a computed property for organization_name would be an alternative. The organization_name details the organization that owns the app and that information is only accessible through org.name inside v-for. Could you provide more clarification or an example on how computed property would be an alternative? I can also change the `isOwner()` function name to `checkAndSetOwner()` to check and set the organization_name.

2024-02-26 19:47 UTC, elmerv commented on source/components/builderv2/AppTransferManager.vue
> +        this.organization_name = org_name
Sounds good. Thank you for the tip, I'll definitely look out for them and look into computed properties in my off time. I'll come back to this code, once I've figured it out. Thanks again for the help and clarification.

2024-02-27 16:58 UTC, vgkids approved these changes

2024-02-27 17:03 UTC, merged