Organizations Component
solid-adventure/trivial-ui pull request #7
Opened 2023-10-13 01:19 UTC by juancarbajal98

**Before**
There was no graphical support to interact with the new [Organizations API](https://github.com/solid-adventure/trivial-api/pull/180) resource so that users could easily create and manage existing organizations.
**After**
A new `OrganizationsManager` component works to display and let the user manage all of their organizations and their users. Adding to a user's Account Settings page, the new Organization section includes intuitive operations to
- Create and Delete organizations
- Create and Delete organization users

The `OrganizationsManager` maintains an instance of an `Organization` for every org it displays. These individual organizations handle event emitting to the org manager for events related to individual organizations.

Demo video at current state:

https://github.com/solid-adventure/trivial-ui/assets/47364801/a0997d00-3a68-46e9-acd9-2259427f4380

While almost all the requests are working as expected, there are some things to tend to before marking this ready for review: 
- Attempting to remove a user from an organization using the new button, regardless of permissions, is returning `404 NOT FOUND`. I have been able to repeatedly do this over Postman successfully. Below are screenshots comparing the UI request versus my Postman request:
![Screenshot 2023-10-12 at 6 03 28 PM](https://github.com/solid-adventure/trivial-ui/assets/47364801/18194897-c6c9-4650-898f-81fc4426ff8e)
![Screenshot 2023-10-12 at 6 03 52 PM](https://github.com/solid-adventure/trivial-ui/assets/47364801/653a3fa4-a697-4e05-a226-7b75aafcb068)
- I have not figured out how to get the current user's email from within `OrganizationsManager`- this was so that in order for a new org to be created all the user needed to provide was a name.
- I still need to test the adding of nonexistent users to organizations and resetting their password with our existing reset password link.
- A complete pass on styling.

2023-10-18 02:41 UTC, juancarbajal98 commented
My most recent push introduced styling that resembles the credentials vault layout + styles. It also converted the `Organization` child component into a better suited `OrganizationUsersManager`. Now the parent component `OrganizationsManager` is responsible for the overall display and management of organizations, and the child component no longer emits an event to modify (in this case, delete) organizations and is only responsible User behavior.

Updated video:

https://github.com/solid-adventure/trivial-ui/assets/47364801/e90e0b17-747a-42fd-bf4e-e35974459c10

The only styling I struggled with was overriding the `HideableSection` button font color styling, it can be seen really lightly where the user clicks "Users" and should be made a darker color.

2023-10-23 15:20 UTC, vgkids requested changes
This is coming along nicely. There's a handful of things before we can merge:

- "Organizations" in the UI instead of "Organizations Manager"
- hide Organization ID in table
- when Users are displayed, they should have name and email, not the JSON
- Confirm when user clicks Delete
- When adding a user, have a dropdown to choose between Admin or Member instead of a text input

2023-10-24 04:02 UTC, juancarbajal98 commented
Thank you for the feedback @vgkids! I was able to get through those changes and am now providing the user with messages for all the relevant operations (very simple form validation and status checking): 

https://github.com/solid-adventure/trivial-ui/assets/47364801/50bb945d-d6aa-4909-bb0d-45f4c7495fdc

I left commented out our usual approach to disappearing messages in the UI, which is setting `this.message = 'a message'` and replace it with a quarter second pause before setting `this.message`. I liked this more when testing but let me know what you think. Would also appreciate any styling tips for the Users layout. Thanks!

2023-12-05 23:56 UTC, vgkids approved these changes

2023-12-06 00:11 UTC, merged